"""empty message

Revision ID: 24210e7b026a
Revises: 3c859fbdee02
Create Date: 2023-08-11 17:36:50.338899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24210e7b026a'
down_revision = '3c859fbdee02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
